export const Env: {
  APP_URL: string
  SUPABASE_URL: string
  SUPABASE_PUBLISHABLE_DEFAULT_KEY: string
  TOKEN_NAME: string
  TOKEN_EXPIRATION: string
  HTTP_REQUEST_TIMEOUT: string
  GMAIL_USER: string
  GMAIL_PASSWORD: string
  JWT_SECRET: string
} = {
  APP_URL: process.env.NEXT_PUBLIC_APP_URL ?? '',
  SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL ?? '',
  SUPABASE_PUBLISHABLE_DEFAULT_KEY:
    process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY ?? '',
  TOKEN_NAME: process.env.NEXT_PUBLIC_TOKEN_NAME ?? '',
  TOKEN_EXPIRATION: process.env.NEXT_PUBLIC_TOKEN_EXPIRATION ?? '',
  HTTP_REQUEST_TIMEOUT: process.env.NEXT_PUBLIC_HTTP_REQUEST_TIMEOUT ?? '',
  GMAIL_USER: process.env.GMAIL_USER ?? '',
  GMAIL_PASSWORD: process.env.GMAIL_PASSWORD ?? '',
  JWT_SECRET: process.env.JWT_SECRET ?? '',
}
