export const Env: {
  APP_URL: string
  SUPABASE_URL: string
  SUPABASE_PUBLISHABLE_DEFAULT_KEY: string
  TOKEN_NAME: string
  TOKEN_EXPIRATION: string
  HTTP_REQUEST_TIMEOUT: string
  RESEND_API_KEY: string
  RESEND_FROM_EMAIL_ORDERS: string
  RESEND_FROM_EMAIL_SUPPORT: string
  JWT_SECRET: string
  LOGO_PATH: string
  META_LOGO_PATH: string
  HERO_IMAGE_PATH: string
} = {
  APP_URL: process.env.NEXT_PUBLIC_APP_URL ?? '',
  SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL ?? '',
  SUPABASE_PUBLISHABLE_DEFAULT_KEY:
    process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY ?? '',
  TOKEN_NAME: process.env.NEXT_PUBLIC_TOKEN_NAME ?? '',
  TOKEN_EXPIRATION: process.env.NEXT_PUBLIC_TOKEN_EXPIRATION ?? '',
  HTTP_REQUEST_TIMEOUT: process.env.NEXT_PUBLIC_HTTP_REQUEST_TIMEOUT ?? '',
  RESEND_API_KEY: process.env.RESEND_API_KEY ?? '',
  RESEND_FROM_EMAIL_ORDERS: process.env.RESEND_FROM_EMAIL_ORDERS ?? '',
  RESEND_FROM_EMAIL_SUPPORT: process.env.RESEND_FROM_EMAIL_SUPPORT ?? '',
  JWT_SECRET: process.env.JWT_SECRET ?? '',
  LOGO_PATH: process.env.LOGO_PATH ?? '',
  META_LOGO_PATH: process.env.META_LOGO_PATH ?? '',
  HERO_IMAGE_PATH: process.env.HERO_IMAGE_PATH ?? '',
}
